import type { AppState } from './api/types';

export const SEED: AppState = {
  meta: {
    jinbeApi: "http://jinbe.local:8080",
    opalServer: "http://opal-server:7002",
    kratosAdmin: "http://kratos-admin:80",
    lastSync: "42s ago",
  },
  services: [
    { name: "jinbe", upstreamUrl: "http://jinbe.local:8080", description: "Platform control plane (RBAC admin)", createdAt: "2025-01-14", routes: 38, roles: 5 },
    { name: "kuma_v2", upstreamUrl: "http://kuma.local:8081", description: "Observability & metrics ingestion", createdAt: "2025-03-02", routes: 22, roles: 4 },
    { name: "global", upstreamUrl: null, description: "Cross-service roles (apply to every service)", createdAt: "2024-12-08", routes: 0, roles: 3 },
    { name: "reporting", upstreamUrl: "http://reporting.local:8080", description: "BI & scheduled reports", createdAt: "2026-04-12", routes: 14, roles: 4 },
  ],
  roles: {
    jinbe: {
      admin: ["*"],
      operator: ["clusters:list","clusters:read","clusters:create","clusters:update","databases:list","databases:read","databases:create"],
      editor: ["databases:list","databases:read","databases:create","databases:update","clusters:list","clusters:read"],
      viewer: ["databases:list","databases:read","clusters:list","clusters:read"],
      billing_reader: ["billing:read","billing:list"],
    },
    kuma_v2: {
      admin: ["*"],
      operator: ["metrics:write","metrics:read","dashboards:read","alerts:create","alerts:update"],
      editor: ["dashboards:read","dashboards:create","dashboards:update","metrics:read"],
      viewer: ["dashboards:read","metrics:read"],
    },
    global: {
      super_admin: ["*"],
      support: ["users:read","audit:read"],
      auditor: ["audit:read","audit:list"],
    },
    reporting: {
      admin: ["*"],
      editor: ["reports:read","reports:create","reports:update","exports:create"],
      viewer: ["reports:read","reports:list"],
      scheduler: ["reports:read","schedules:read","schedules:create","schedules:update"],
    },
  },
  groups: {
    super_admins: { global: ["super_admin"], jinbe: ["admin"], kuma_v2: ["admin"], reporting: ["admin"] },
    admins: { jinbe: ["admin"], kuma_v2: ["admin"], reporting: ["editor"] },
    infra: { jinbe: ["operator"], kuma_v2: ["operator"] },
    devs: { jinbe: ["editor"], kuma_v2: ["editor"] },
    viewers: { jinbe: ["viewer"], kuma_v2: ["viewer"], reporting: ["viewer"] },
    users: { jinbe: ["viewer"] },
    finance: { jinbe: ["billing_reader"], reporting: ["editor"] },
    on_call: { global: ["support"], jinbe: ["operator"], kuma_v2: ["operator"] },
  },
  users: [
    { id: "u_01", name: "Maxime Laurent", email: "maxime@example.io", groups: ["super_admins"], title: "Founding engineer", active: true, last: "2m ago" },
    { id: "u_02", name: "Am\u00e9lie Rousseau", email: "amelie@example.io", groups: ["admins","on_call"], title: "Platform lead", active: true, last: "14m ago" },
    { id: "u_03", name: "Jules Perret", email: "jules@example.io", groups: ["infra","on_call"], title: "SRE", active: true, last: "1h ago" },
    { id: "u_04", name: "Sana Bouchikhi", email: "sana@example.io", groups: ["devs"], title: "Senior engineer", active: true, last: "32m ago" },
    { id: "u_05", name: "Leo Tanaka", email: "leo@example.io", groups: ["devs"], title: "Backend engineer", active: true, last: "3h ago" },
    { id: "u_06", name: "Priya Rao", email: "priya@example.io", groups: ["devs"], title: "Backend engineer", active: true, last: "18m ago" },
    { id: "u_07", name: "Noor Haddad", email: "noor@example.io", groups: ["admins"], title: "Security eng.", active: true, last: "56m ago" },
    { id: "u_08", name: "Felix Marchetti", email: "felix@example.io", groups: ["devs","on_call"], title: "Full-stack", active: true, last: "4h ago" },
    { id: "u_09", name: "Ingrid S\u00f8rensen", email: "ingrid@example.io", groups: ["viewers"], title: "PM", active: true, last: "2d ago" },
    { id: "u_10", name: "Yassine El Amrani", email: "yassine@example.io", groups: ["devs"], title: "ML engineer", active: true, last: "6h ago" },
    { id: "u_11", name: "Rhea Kapoor", email: "rhea@example.io", groups: ["finance"], title: "Finance ops", active: true, last: "1d ago" },
    { id: "u_12", name: "Victor Leclerc", email: "victor@example.io", groups: ["finance","viewers"], title: "CFO", active: true, last: "3d ago" },
    { id: "u_13", name: "Miriam Cohen", email: "miriam@example.io", groups: ["users"], title: "Support", active: true, last: "8h ago" },
    { id: "u_14", name: "Tobias Jansen", email: "tobias@example.io", groups: ["devs"], title: "Backend engineer", active: true, last: "47m ago" },
    { id: "u_15", name: "Claire Okafor", email: "claire@example.io", groups: ["devs","viewers"], title: "Designer", active: true, last: "5h ago" },
    { id: "u_16", name: "Diego Alvarado", email: "diego@example.io", groups: ["infra"], title: "Infra engineer", active: true, last: "2h ago" },
    { id: "u_17", name: "Hana Fujimoto", email: "hana@example.io", groups: ["users"], title: "Intern", active: true, last: "12h ago" },
    { id: "u_18", name: "Paul Bernardin", email: "paul@example.io", groups: ["viewers"], title: "Board observer", active: true, last: "11d ago" },
    { id: "u_19", name: "Renata Duarte", email: "renata@example.io", groups: [], title: "New hire", active: false, last: "never" },
    { id: "u_20", name: "Omar Benchekroun", email: "omar@example.io", groups: ["on_call"], title: "SRE", active: true, last: "1h ago" },
  ],
  routeMaps: {
    jinbe: [
      { method: "GET", path: "/api/health" },
      { method: "GET", path: "/api/clusters/", permission: "clusters:list" },
      { method: "GET", path: "/api/clusters/:id", permission: "clusters:read" },
      { method: "POST", path: "/api/clusters/", permission: "clusters:create" },
      { method: "PATCH", path: "/api/clusters/:id", permission: "clusters:update" },
      { method: "DELETE", path: "/api/clusters/:id", permission: "clusters:delete" },
      { method: "GET", path: "/api/databases/", permission: "databases:list" },
      { method: "GET", path: "/api/databases/:id", permission: "databases:read" },
      { method: "POST", path: "/api/databases/", permission: "databases:create" },
      { method: "PUT", path: "/api/databases/:id", permission: "databases:update" },
      { method: "DELETE", path: "/api/databases/:id", permission: "databases:delete" },
      { method: "GET", path: "/api/billing/invoices", permission: "billing:read" },
      { method: "GET", path: "/api/admin/git-config/:any*", permission: "admin:read" },
      { method: "GET", path: "/api/admin/rbac/:any*", permission: "admin:read" },
    ],
    kuma_v2: [
      { method: "GET", path: "/api/health" },
      { method: "GET", path: "/api/dashboards/", permission: "dashboards:read" },
      { method: "POST", path: "/api/dashboards/", permission: "dashboards:create" },
      { method: "PUT", path: "/api/dashboards/:id", permission: "dashboards:update" },
      { method: "GET", path: "/api/metrics/:any*", permission: "metrics:read" },
      { method: "POST", path: "/api/metrics/ingest", permission: "metrics:write" },
      { method: "POST", path: "/api/alerts/", permission: "alerts:create" },
    ],
    reporting: [
      { method: "GET", path: "/api/health" },
      { method: "GET", path: "/api/reports/", permission: "reports:list" },
      { method: "GET", path: "/api/reports/:id", permission: "reports:read" },
      { method: "POST", path: "/api/reports/", permission: "reports:create" },
      { method: "POST", path: "/api/exports/", permission: "exports:create" },
      { method: "GET", path: "/api/schedules/", permission: "schedules:read" },
    ],
    global: [],
  },
  accessRules: [
    {
      id: "jinbe-authenticated",
      service: "jinbe",
      match: { url: "<http|https>://<{api,auth}.example.io>/api/<**>", methods: ["GET","POST","PUT","PATCH","DELETE"] },
      authenticators: ["cookie_session","bearer_token"],
      authorizer: "remote_json",
      opaUrl: "http://opa:8181/v1/data/authz/allow",
      mutators: ["header"],
      upstream: "http://jinbe.local:8080",
    },
    {
      id: "jinbe-health",
      service: "jinbe",
      match: { url: "<http|https>://<{api,auth}.example.io>/api/health", methods: ["GET"] },
      authenticators: ["noop"],
      authorizer: "allow",
      mutators: ["noop"],
      upstream: "http://jinbe.local:8080",
    },
    {
      id: "kuma-authenticated",
      service: "kuma_v2",
      match: { url: "<http|https>://metrics.example.io/api/<**>", methods: ["GET","POST","PUT","DELETE"] },
      authenticators: ["cookie_session","bearer_token"],
      authorizer: "remote_json",
      opaUrl: "http://opa:8181/v1/data/authz/allow",
      mutators: ["header"],
      upstream: "http://kuma.local:8081",
    },
    {
      id: "reporting-authenticated",
      service: "reporting",
      match: { url: "<http|https>://reports.example.io/api/<**>", methods: ["GET","POST"] },
      authenticators: ["cookie_session","bearer_token"],
      authorizer: "remote_json",
      opaUrl: "http://opa:8181/v1/data/authz/allow",
      mutators: ["header"],
      upstream: "http://reporting.local:8080",
    },
  ],
  audit: [
    { id: "e_201", when: "12s ago", ts: "2026-04-24 14:32:48", who: "felix@example.io", category: "access", verb: "allow", target: "GET /api/clusters", service: "jinbe", ip: "10.12.4.88", ua: "Chrome 124 / macOS" },
    { id: "e_200", when: "34s ago", ts: "2026-04-24 14:32:26", who: "felix@example.io", category: "auth", verb: "login", target: "oauth2 \u00b7 google", ip: "10.12.4.88", ua: "Chrome 124 / macOS", mfa: true },
    { id: "e_199", when: "1m ago", ts: "2026-04-24 14:31:40", who: "amelie@example.io", category: "rbac", verb: "assign", target: "omar@example.io \u2192 on_call", status: "applied" },
    { id: "e_198", when: "2m ago", ts: "2026-04-24 14:30:52", who: "system", category: "system", verb: "sync", target: "OPAL \u2192 OPA bundle v42", status: "applied" },
    { id: "e_197", when: "3m ago", ts: "2026-04-24 14:29:11", who: "leo@example.io", category: "access", verb: "deny", target: "DELETE /api/databases/prod-eu-1", service: "jinbe", ip: "10.12.3.42", reason: "missing databases:delete" },
    { id: "e_196", when: "5m ago", ts: "2026-04-24 14:27:03", who: "priya@example.io", category: "access", verb: "allow", target: "POST /api/clusters/kube-prod/restart", service: "jinbe", ip: "10.12.3.18" },
    { id: "e_195", when: "7m ago", ts: "2026-04-24 14:25:40", who: "jules@example.io", category: "auth", verb: "mfa", target: "totp challenge", ip: "10.12.3.9", ua: "Firefox 126 / Linux", mfa: true },
    { id: "e_194", when: "12m ago", ts: "2026-04-24 14:20:18", who: "amelie@example.io", category: "rbac", verb: "create", target: "group:finance", status: "applied" },
    { id: "e_193", when: "18m ago", ts: "2026-04-24 14:14:02", who: "system", category: "auth", verb: "expire", target: "session \u00b7 yassine@example.io", ip: "10.12.5.77" },
    { id: "e_192", when: "23m ago", ts: "2026-04-24 14:09:31", who: "noor@example.io", category: "policy", verb: "update", target: "rego: allow_admin.write \u2192 stricter", status: "applied" },
    { id: "e_191", when: "31m ago", ts: "2026-04-24 14:01:50", who: "maxime@example.io", category: "rbac", verb: "update", target: "role:admin permissions +3 / -1", status: "applied" },
    { id: "e_190", when: "41m ago", ts: "2026-04-24 13:51:12", who: "amelie@example.io", category: "service", verb: "update", target: "roles.reporting.json / scheduler", status: "applied" },
    { id: "e_189", when: "56m ago", ts: "2026-04-24 13:36:04", who: "anon", category: "auth", verb: "fail", target: "login \u00b7 unknown@evilcorp.io", ip: "203.0.113.9", reason: "identity not found" },
    { id: "e_188", when: "1h ago", ts: "2026-04-24 13:29:18", who: "jules@example.io", category: "route", verb: "add", target: "route_map.jinbe.json + 2 routes", status: "applied" },
    { id: "e_187", when: "1h ago", ts: "2026-04-24 13:24:55", who: "diego@example.io", category: "access", verb: "deny", target: "GET /api/admin/rbac/roles", service: "jinbe", ip: "10.12.7.14", reason: "not in admins" },
    { id: "e_186", when: "2h ago", ts: "2026-04-24 12:51:02", who: "ingrid@example.io", category: "auth", verb: "login", target: "oauth2 \u00b7 google", ip: "10.12.2.99", ua: "Safari 17 / macOS", mfa: true },
    { id: "e_185", when: "2h ago", ts: "2026-04-24 12:46:31", who: "sana@example.io", category: "auth", verb: "logout", target: "session ended", ip: "10.12.6.5" },
    { id: "e_184", when: "3h ago", ts: "2026-04-24 11:48:19", who: "amelie@example.io", category: "service", verb: "create", target: "service:reporting", status: "applied" },
    { id: "e_183", when: "4h ago", ts: "2026-04-24 10:42:00", who: "anon", category: "auth", verb: "fail", target: "login \u00b7 brute \u00b7 7 attempts", ip: "198.51.100.22", reason: "rate_limit" },
    { id: "e_182", when: "5h ago", ts: "2026-04-24 09:31:26", who: "noor@example.io", category: "rbac", verb: "revoke", target: "viewers \u27c2 databases:read (jinbe)", status: "applied" },
  ],
};
